---
title: "Visualizing Institution Mobility Vectors"
author: "Dakota Murray"
output: html_notebook
---


```{r}
library(tidyverse)
library(readr)
library(plotly)

inst_coords <- read_csv("/Users/dakotamurray/Dropbox/SME-dropbox/Figures/UMAP/USA/d200/data/2014-2019_USA_umap_d200_euclidean_neighbors20_mindist0.0_data.csv")

inst_lookup <- read_delim("/Users/dakotamurray/Dropbox/SME-dropbox/Data/Additional/institution_lookup_with_states.txt", delim = "\t") 
country_lookup <- read_delim("/Users/dakotamurray/Dropbox/SME-dropbox/Data/Additional/iso_to_country.txt", delim = "\t")
country_lookup
```



```{r}
inst_coords_details <- inst_coords %>%
  left_join(inst_lookup, by = c("token" = "cwts_org_no")) %>%
  left_join(country_lookup, by = c("country_iso_alpha" = "Alpha_code_3"))

inst_coords
inst_coords_details
```


```{r}
org_types = unique(inst_coords_details$org_type)
org_types_simplified <- c(
  "University" = "Univ",
  "Research organisation" = "Institute",
  "Hospital" = "Hospital",
  "Teaching Organisation" = "Other",
  "Governmental Institution" = "Gov",
  "Funding Organisation" = "Gov",
  "Funding Channel" = "Gov",
  "University Component" = "Univ",
  "Hospital Group" = "Hospital",
  "Teaching Organisation" = "Other",
  "Ambiguous" = "Other",
  "Collegiate University" = "Univ"
)


g <- inst_coords_details %>%
  filter(!is.na(Continent_name)) %>%
  mutate(org_type = plyr::mapvalues(org_type, from = names(org_types_simplified), to = org_types_simplified)) %>%
  ggplot(aes(x = axis1, y = axis2, fill = org_type, group = city, label = full_name, label2 = Country_name, label3 = org_type, label4 = region)) +
  geom_point(size = 3, alpha = 0.9, shape = 21, color = "black") +
  theme_minimal() +
  guides(color = guide_legend(override.aes = list(size=5)),
         shape = guide_legend(override.aes = list(size=5))) +
  scale_fill_brewer(palette = "Accent") +
  theme(legend.position = "bottom")

#ggsave("~/Desktop/mobility_institution_bycontinent.pdf", g, width = 10, height = 8)
g
ggplotly(g, tooltip = c("Continent_name", "Country_name", "region", "city", "full_name", "org_type", "org"))
```

```{r}
city_lookup <- inst_lookup %>%
  select(c(city_country, city, country_iso_alpha)) %>%
  group_by(city_country) %>%
  slice(1) %>% 
  rowwise() %>%
  mutate(city_country = gsub("[ ]", "_", city_country))

city_lookup
city_coords <- read_csv("/Users/dakotamurray/Dropbox/SME-dropbox/Figures/UMAP/data/city_2014-2019_umap_data.csv") %>%
  left_join(city_lookup, by = c("token" = "city_country")) %>%
  left_join(country_lookup, by = c("country_iso_alpha" = "Alpha_code_3"))

g <- city_coords %>%
  ggplot(aes(x = axis1, y = axis2,  label = token, color = Continent_name, label2 = Country_name)) +
  geom_point(size = 0.8, alpha = 0.8) +
  theme_minimal() +
  guides(color = guide_legend(override.aes = list(size=5)),
         shape = guide_legend(override.aes = list(size=5))) +
  scale_color_brewer(palette = "Set2") +
  theme(legend.position = "bottom")

ggplotly(g, tooltip = c("token", "name", "Continent_name", "Country_name"))

unique(city_coords$labels)
```


```{r}
country_coords <- read_csv("/Users/dakotamurray/Dropbox/SME-dropbox/Figures/UMAP/data/country_2008-2013_umap_data.csv") %>%
  left_join(country_lookup, by = c("token" = "Alpha_code_3"))

g <- country_coords %>%
  filter(!is.na(Continent_name)) %>%
  ggplot(aes(x = axis1, y = axis2,  label = token, label2 = Country_name, color = Continent_name, shape = Continent_name)) +
  #geom_point(size = 1.2, alpha = 0.8) +
  theme_minimal() +
  geom_text() +
  guides(color = guide_legend(override.aes = list(size=5)),
         shape = guide_legend(override.aes = list(size=5))) +
  scale_color_brewer(palette = "Set2") +
  theme(legend.position = "bottom")

ggplotly(g, tooltip = c("labels", "Continent_name", "Country_name"))
```


```{r}
country_coords <- read_csv("/Users/dakotamurray/Dropbox/SME-dropbox/Figures/UMAP/data/country_2014-2019_umap_data.csv") %>%
  left_join(country_lookup, by = c("token" = "Alpha_code_3"))

g <- country_coords %>%
  filter(!is.na(Continent_name)) %>%
  ggplot(aes(x = axis1, y = axis2,  label = token, label2 = Country_name, color = Continent_name, shape = Continent_name)) +
  #geom_point(size = 1.2, alpha = 0.8) +
  theme_minimal() +
  geom_text() +
  guides(color = guide_legend(override.aes = list(size=5)),
         shape = guide_legend(override.aes = list(size=5))) +
  scale_color_brewer(palette = "Set2") +
  theme(legend.position = "bottom")

ggplotly(g, tooltip = c("labels", "Continent_name", "Country_name"))
```