from os.path import join as osjoin


PROJ_HOME = open('PROJ_HOME_DIR').read().strip()
DATA_DIR = osjoin(PROJ_HOME, 'Data')
FIGURE_DIR = osjoin(PROJ_HOME, 'Figures')
ASSET_DIR = osjoin(PROJ_HOME, 'Assets')
ADDITIONAL_DATA_DIR = osjoin(DATA_DIR, 'Additional')
DERIVED_DATA_DIR = osjoin(DATA_DIR, 'Derived')
EMBEDDINGS_DIR = osjoin(PROJ_HOME, 'Archive','Embeddings_20191209','word2vec')
CLUSTERING_FIGURE_DIR = osjoin(FIGURE_DIR, 'Clustering')

# Assets
FONT_PATH = osjoin(ASSET_DIR, 'Helvetica.ttf')
BOLD_FONT_PATH = osjoin(ASSET_DIR, 'helvetica-bold.ttf')

# Meta_info_files 
EMBEDDING_FILE_DIR = osjoin(EMBEDDINGS_DIR, "2008-2019_word2vec_d200_ws2_model.bin")
INST_LOOK_UP_FILE_DIR = osjoin(ADDITIONAL_DATA_DIR , "institution_lookup_with_states.txt")
COUNTRY_META_FILE_DIR = osjoin(ADDITIONAL_DATA_DIR , "country_metadata.csv")

# Config
LEVEL_LIST = ['country']


# Reult Files
DENDROGRAM_FILES = [osjoin(CLUSTERING_FIGURE_DIR, 'clustering_{}_dendrogram_part.pdf'.format(level)) for level in LEVEL_LIST]
HEATMAP_FILES = [osjoin(CLUSTERING_FIGURE_DIR, 'clustering_{}_heatmap_part.pdf'.format(level)) for level in LEVEL_LIST]
CLUSIM_FILES = [osjoin(CLUSTERING_FIGURE_DIR, 'clustering_{}_clusim_part.pdf'.format(level)) for level in LEVEL_LIST]

rule all:
    input:
        DENDROGRAM_FILES,
        HEATMAP_FILES,
        CLUSIM_FILES
        
rule draw_cluster_result_country:
    input:
        EMBEDDING_FILE_DIR,
        INST_LOOK_UP_FILE_DIR,
        COUNTRY_META_FILE_DIR,
        FONT_PATH,
        BOLD_FONT_PATH
    output:
        osjoin(CLUSTERING_FIGURE_DIR, 'clustering_country_dendrogram_part.pdf'),
        osjoin(CLUSTERING_FIGURE_DIR, 'clustering_country_heatmap_part.pdf'),
        osjoin(CLUSTERING_FIGURE_DIR, 'clustering_country_clusim_part.pdf')
    run:
        shell('python3 script/draw_clustering_figure_country_level.py {input} {output}')
